# Mail properties. Enable less secure apps if using Gmail id
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    port: 587
    protocol: smtp
    debug: true

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#spring.mail.default-encoding=UTF-8
#spring.mail.host=smtp.gmail.com
#spring.mail.username=${MAIL_ADDRESS}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.port=587
#spring.mail.protocol=smtp
#spring.mail.debug=true
#spring.mail.smtp.auth=true
#spring.mail.smtp.starttls.enable=true